name: 'Auto Assign PR'
description: 'auto assign PRs to reviewers'
inputs:
  draft-approvers: 
    description: 'list of users to pull from when assigning draft PRs'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
