name: "Auto-Assign"
on: 
  pull_request:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    # - run: npm test
    - uses: ./
      with:
        draft-approvers: '["dave-campbell", "bvandorn"]'
        github-token: ${{ secrets.GITHUB_TOKEN }}
